from .auth_serializer import UserRegistrationSerializer, UserLoginSerializer, SupplierSerializer,\
CustomerSerializer,UserUpdateSerializer,ChangePasswordSerializer,UserSerializer,SupplierCreateSerializer

# admin
from .admin.manage_serializer import CustomerSupplierUserSerializer,ProductSerializer,CreateProductSerializer,CategorySerializer,UpdateProductSerializer
from .admin.report import StockReportSerializer,ReportRevenueSerializer,ReportInvoicePurchaseSerializer,ReportInvoiceOrderSerializer
from .admin.purchase_serializer import PaymentPurchaseCreateSerializer,ProductSerializer,PurchaseSerializer,\
PurchaseDetailSerializer,InventorySerializer,CreatePurchaseSerializer
from .admin.inventory_serializer import InventorySerializer,InventoryDetailSerializer
from .admin.invoice.invoice_serializer import InvoicePurchaseSerializer,InvoiceOrderSerializer
# supplier
from .supplier.prosal_product import ProposalProductSerializer,ProposalProductAdminSerializer
from .supplier.main import OrderDetailSerializer,HistoryStockSerializer
from .supplier.manage_product_serializer import ProductSupplierSerializer
from .supplier.manage_purchase_serializer import PurchaseSerializer,PurchaseDetailSerializer
# customer
from .customer.cart_serializer import CartItemSerializer,CartSerializer