# Generated by Django 5.2.5 on 2025-08-27 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(choices=[('kho HCM', 'Kho HCM'), ('kho HN', 'Kho HN'), ('kho DN', 'Kho DN')], default='kho HCM', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ProductProposals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_stock', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='manage_app.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='manage_app.supplier')),
            ],
        ),
    ]
