# Generated by Django 5.2.5 on 2025-08-29 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_user_is_block_alter_inventory_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='InvoiceOrder',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentOrder',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchaseID', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('canceled', 'Canceled')], default='unpaid', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchaseDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='StockExport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('export_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
