# Generated by Django 5.2.5 on 2025-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_rename_invoice_invoiceorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('supplier', 'Supplier')], default='customer', max_length=10),
        ),
    ]
