# Generated by Django 5.2.5 on 2025-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
