# Generated by Django 5.2.5 on 2025-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0007_alter_product_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
