# Generated by Django 5.2.5 on 2025-09-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0008_invoiceorder_method_invoicepurchase_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentpurchase',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], max_length=50),
        ),
    ]
