# Generated by Django 5.2.5 on 2025-09-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0009_alter_invoiceorder_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='method',
            field=models.CharField(choices=[('vnpay', 'VNPAY'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='method',
            field=models.CharField(choices=[('vnpay', 'VNPAY'), ('cash', 'Cash')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('vnpay', 'VNPAY'), ('cash', 'Cash')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentpurchase',
            name='payment_method',
            field=models.CharField(choices=[('vnpay', 'VNPAY'), ('cash', 'Cash')], max_length=50),
        ),
    ]
