# Generated by Django 5.2.5 on 2025-09-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0010_alter_invoiceorder_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('canceled', 'Canceled')], default='unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('canceled', 'Canceled')], default='unpaid', max_length=50),
        ),
    ]
