# Generated by Django 5.2.5 on 2025-09-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0011_alter_invoiceorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
