# Generated by Django 5.2.5 on 2025-09-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0012_purchase_created_at_purchase_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_at',
        ),
    ]
