# Generated by Django 5.2.5 on 2025-09-08 13:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0013_remove_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockexport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockexport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
