# Generated by Django 5.2.6 on 2025-09-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0014_stockexport_created_at_stockexport_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
