# Generated by Django 5.2.6 on 2025-09-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0015_invoiceorder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.inventory'),
        ),
    ]
