# Generated by Django 5.2.6 on 2025-09-16 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0016_cartitem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.inventory'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_app.inventory'),
        ),
    ]
