# Generated by Django 5.2.6 on 2025-09-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0017_orderdetail_inventory_purchasedetail_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
