# Generated by Django 5.2.6 on 2025-09-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0018_alter_invoiceorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
